### ISSUE TITLE
TypeError: process.argv.includes is not a function

### ISSUE THREAD

**Issue by gardner** [kriasoft/react-static-boilerplate#107]
node version: v5.9.0
npm version: 3.7.3
platform: osx
version manager: nvm

**Steps to reproduce**

    git clone -o react-static-boilerplate -b master --single-branch       https://github.com/kriasoft/react-static-boilerplate.git www
    cd www
    npm install
    npm run build

Result:

```
Starting 'build'...
Starting 'clean'...
Finished 'clean' after 6ms
Starting 'bundle'...
TypeError: process.argv.includes is not a function
    at Object.<anonymous> (/Users/gardner/src/www/webpack.config.js:19:64)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/gardner/src/www/run.js:74:25
    at /Users/gardner/src/www/run.js:35:54
Starting 'html'...
TypeError: process.argv.includes is not a function
    at Object.<anonymous> (/Users/gardner/src/www/webpack.config.js:19:64)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/gardner/src/www/run.js:49:25
    at /Users/gardner/src/www/run.js:35:54
Starting 'sitemap'...
Finished 'sitemap' after 8ms
Finished 'build' after 43ms
```

**Comment by frenzzy** [comment]
> [Getting Started](https://github.com/kriasoft/react-static-boilerplate#getting-started)
> **NODE:** Make sure that you have [Node.js](https://nodejs.org/) v6 installed on your local machine.

**Comment by gardner** [comment]
Sorry that I missed that in the Getting Started documents. Thank you for the quick reply!
