### ISSUE TITLE
error during node run publish

### ISSUE THREAD

**Issue by uragecz** [kriasoft/react-static-boilerplate#108]
Hi, i just downloaded your starter kit, first i runned npm install, then node run, everything were alright until i wrote node run publish. After i put google code, i get:
```
Starting 'publish'...
Starting 'build'...
Starting 'clean'...
Finished 'clean' after 28ms
Starting 'bundle'...
Time: 12288ms
                       Asset     Size  Chunks             Chunk Names
   0.7b379aac6fe623d77e93.js  4.19 kB       0  [emitted]
main.e630723519d349cb3775.js   297 kB       1  [emitted]  main
Finished 'bundle' after 12448ms
Starting 'html'...
Finished 'html' after 0ms
Starting 'sitemap'...
Finished 'sitemap' after 16ms
Finished 'build' after 12492ms
Error
    at Error.FirebaseError (C:\Users\User\Desktop\Work\react-static-boilerplate-master\node_modules\firebase-tools\lib\error.js:11:17)
    at module.exports (C:\Users\User\Desktop\Work\react-static-boilerplate-master\node_modules\firebase-tools\lib\responseToError.js:28:10)
    at Request._callback (C:\Users\User\Desktop\Work\react-static-boilerplate-master\node_modules\firebase-tools\lib\api.js:30:23)
    at Request.self.callback (C:\Users\User\Desktop\Work\react-static-boilerplate-master\node_modules\request\request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\User\Desktop\Work\react-static-boilerplate-master\node_modules\request\request.js:1082:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\User\Desktop\Work\react-static-boilerplate-master\node_modules\request\request.js:1009:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:973:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
any tips what to do?

**Comment by koistya** [comment]
@uragecz does manual deployment via Firebase CLI work for you?

```sh
$ node run build
$ firebase deploy
```

**Comment by koistya** [comment]
I will close for now. Feel free to re-open if you can provide more info to reproduce this issue.

**Comment by MaicolBen** [comment]
I've the same problem, if I do with the `firebase-cli`, it throws `Invalid CLI version provided. - Please update to at least v2.0.0 by running npm update -g firebase-cli`

I tried to update but nothing happens

I've firebase-cli 1.2.0

**Comment by cupojoe** [comment]
I'm getting the same error.
