### ISSUE TITLE
CSS ImportLoader

### ISSUE THREAD

**Issue by psamim** [kriasoft/react-static-boilerplate#122]
Hi,

When I add my CSS file to the entry array in the webpack config file, I receive the following error upon build:

```
ERROR in ./assets/css/icons/summernote/summernote.ttf?ad8d7e2d177d2473aecd9b35d16211fb
Module parse failed: /home/samim/workspace/react-static/assets/css/icons/summernote/summernote.ttf?ad8d7e2d177d2473aecd9b35d16211fb Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '' (1:0)
    at Parser.pp.raise (/home/samim/workspace/react-static/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.getTokenFromCode (/home/samim/workspace/react-static/node_modules/acorn/dist/acorn.js:2831:8)
    at Parser.pp.readToken (/home/samim/workspace/react-static/node_modules/acorn/dist/acorn.js:2526:15)
    at Parser.pp.nextToken (/home/samim/workspace/react-static/node_modules/acorn/dist/acorn.js:2518:71)
    at Parser.parse (/home/samim/workspace/react-static/node_modules/acorn/dist/acorn.js:1631:10)
    at Object.parse (/home/samim/workspace/react-static/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/home/samim/workspace/react-static/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/samim/workspace/react-static/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/samim/workspace/react-static/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/samim/workspace/react-static/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/samim/workspace/react-static/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/samim/workspace/react-static/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/samim/workspace/react-static/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./~/css-loader!./assets/css/components.css 6:95181-95264
```

This is the entry array in webpack config:
```js
  entry: [
      '!!style!css!./assets/css/components.css',
      './assets/js/core/libraries/bootstrap.min.js',
      './main.js',
  ],
```
Thanks

**Comment by psamim** [comment]
I solved the problem. The problem was that the test regex, `/\.(eot|ttf|wav|mp3)$/` did not match my file names (summernote.ttf?ad8d7e2d177d2473aecd9b35d16211fb).
