### ISSUE TITLE
node run build - error

### ISSUE THREAD

**Issue by iongion** [kriasoft/react-static-boilerplate#125]
I could not go past the `node run build` phase:

```
W:\Workspace\MyApp> node --version
v5.7.0
W:\Workspace\MyApp> node run build
W:\Workspace\MyApp\run.js:113
  let count = 0;
  ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by koistya** [comment]
@iongion it requires Node.js v6 (or higher), you can either upgrade to v6 or install Node.js 6 via **nvm** if you need to have multiple versions of Node.js installed on your development machine yet being able to switch between them.

**Comment by seanh1414** [comment]
@koistya I had this error and it was totally the issue - I forgot I was running 4.3 for lambda work. Thanks!
