### ISSUE TITLE
node run publish gives error

### ISSUE THREAD

**Issue by bernatfortet** [kriasoft/react-static-boilerplate#129]
Just following the boilerplate instructions, without touching anything I get this error:

```
node run publish
Starting 'publish'...
Starting 'build'...
Starting 'clean'...
Finished 'clean' after 9ms
Starting 'bundle'...
Time: 10159ms
                       Asset     Size  Chunks             Chunk Names
   0.62e754d958e21f5ae018.js  4.39 kB       0  [emitted]
main.514320d4ba2398c1c451.js   502 kB       1  [emitted]  main
Finished 'bundle' after 10228ms
Starting 'html'...
Finished 'html' after 2ms
Starting 'sitemap'...
Finished 'sitemap' after 1ms
Finished 'build' after 10242ms
? Allow Firebase to collect anonymous CLI usage information? Yes
? Paste authorization code here: 4/x-N1LtcH9JOeXF6xcSZ6yvYmX7uw057Rj0QZ9ygtxp0
Error
    at Error.FirebaseError (/Users/bernat/Dropbox/Bernat/Projects/Surf Coach/products/coacher/node_modules/firebase-tools/lib/error.js:11:17)
    at /Users/bernat/Dropbox/Bernat/Projects/Surf Coach/products/coacher/node_modules/firebase-tools/lib/requireAccess.js:45:26
    at lib$rsvp$$internal$$tryCatch (/Users/bernat/Dropbox/Bernat/Projects/Surf Coach/products/coacher/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/bernat/Dropbox/Bernat/Projects/Surf Coach/products/coacher/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/bernat/Dropbox/Bernat/Projects/Surf Coach/products/coacher/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/bernat/Dropbox/Bernat/Projects/Surf Coach/products/coacher/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by dylntrnr** [comment]
@bernatfortet I had this, saw https://github.com/kriasoft/react-static-boilerplate/issues/108 and ended up needing to connect my firebase account to my google account, then upgrade my firebase-tools, create a project in firebase, and follow the instructions there. Then I was able to `firebase deploy` to get it live.

**Comment by mksarge** [comment]
In case anyone has similar issues:

First, make sure you've created a Firebase project and updated `run.js` with your Firebase project's ID, not name. (The [docs](https://github.com/kriasoft/react-static-boilerplate#how-to-deploy) should be amended to explicitly state this.)

If you want to deploy manually, make sure you `npm install -g firebase-tools` instead of the deprecated `firebase-cli`.
