### ISSUE TITLE
Path is not defined when trying to publish to Github Pages

### ISSUE THREAD

**Issue by ethanneff** [kriasoft/react-static-boilerplate#189]
Cannot publish to Github pages. Documentation has an error. https://github.com/kriasoft/react-static-boilerplate/blob/master/docs/recipes/deploy-to-github-pages.md

Code:
```node
tasks.set('publish', () => {
  const remote = {
    url: 'https://github.com/<owner>/<repo>.git', // TODO: Update deployment URL
    branch: 'gh-pages',
  };
  global.DEBUG = process.argv.includes('--debug') || false;
  const spawn = require('child_process').spawn;
  const opts = { cwd: path.resolve(__dirname, './public'), stdio: ['ignore', 'inherit', 'inherit'] };
  const git = (...args) => new Promise((resolve, reject) => {
    spawn('git', args, opts).on('close', code => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`git ${args.join(' ')} => ${code} (error)`));
      }
    });
  });

  return Promise.resolve()
    .then(() => run('clean'))
    .then(() => git('init', '--quiet'))
    .then(() => git('config', '--get', 'remote.origin.url')
      .then(() => git('remote', 'set-url', 'origin', remote.url))
      .catch(() => git('remote', 'add', 'origin', remote.url))
    )
    .then(() => git('ls-remote', '--exit-code', remote.url, 'master')
      .then(() => Promise.resolve()
        .then(() => git('fetch', 'origin'))
        .then(() => git('reset', `origin/${remote.branch}`, '--hard'))
        .then(() => git('clean', '--force'))
      )
      .catch(() => Promise.resolve())
    )
    .then(() => run('build'))
    .then(() => git('add', '.', '--all'))
    .then(() => git('commit', '--message', new Date().toUTCString())
      .catch(() => Promise.resolve()))
    .then(() => git('push', 'origin', `HEAD:${remote.branch}`, '--force', '--set-upstream'));
});
```

Error:
```bash
$ node run publish
Starting 'publish'...
ReferenceError: path is not defined
    at tasks.set (/Users/eneff/Desktop/react static/run.js:105:23)
    at Promise.resolve.then (/Users/eneff/Desktop/react static/run.js:31:54)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by ethanneff** [comment]
created #190 to solve issue

**Comment by souloikj** [comment]
Hey @ethanneff , how did you get this to work? 

When I add the publish task as above, I get this:
```shell
node tools/run publish
Starting 'run:publish'...
ReferenceError: tasks is not defined
    at Promise (/Users/qsang/whitespace/werewolves/werewolves-web/tools/run.js:63:3)
    at module.exports.task (/Users/qsang/whitespace/werewolves/werewolves-web/tools/run.js:23:36)
    at Promise.resolve.then (/Users/qsang/whitespace/werewolves/werewolves-web/tools/task.js:26:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I had to change mine to `task("publish", () => {...})`, but then it does not publish to github pages, but I just get the result like I run `node tools/run`.
