### ISSUE TITLE
node run publish generates error for aws s3 deployment

### ISSUE THREAD

**Issue by jackywhlee** [kriasoft/react-static-boilerplate#195]
Following this guide: https://github.com/kriasoft/react-static-boilerplate/blob/master/docs/recipes/deploy-to-amazon-s3.md

Followed step 1 -> 3

When I do step 4: node run publish, I get the following error:

```
module.js:457
    throw err;
    ^

Error: Cannot find module '/home/magi/tideisun/isunico/run'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I'm using nvm, have tried node 6.0, 6.5, and latest 6.9. 

Have tried clearing npm cache, removed node_modules, tried npm install instead of yarn, but it appears nothing I do can change this error. It appears to have nothing to do with the run.js file

**Comment by koistya** [comment]
It should be either `yarn run publish` or `node tools/publish.js`.. also you would need to tweak `tools/config.js` to set the deployment destination. Need to update the docs.

**Comment by Kar1Huang** [comment]
@jackywhlee if you want to deploy to s3 instead of firebase, try below
```
const task = require('./task');
const s3 = require('s3');

// deploy the app to Firebase
global.DEBUG = process.argv.includes('--debug') || false;

module.exports = task('publish', () => new Promise((resolve, reject) => {
  const client = s3.createClient({
    s3Options: {
      region: '_yourregion_',
      sslEnabled: true,
    },
  });
  const uploader = client.uploadDir({
    localDir: 'public',
    deleteRemoved: true,
    s3Params: { Bucket: '_yourbucket_' }, 
  });
  uploader.on('error', reject);
  uploader.on('end', resolve);
}));
```

**Comment by kungfoolabs** [comment]
Hmm. I had problems because build wasn't run on upload. Changed to the following

```
const path = require('path');
const s3 = require('s3');
const build = require('./build');
const task = require('./task');
const config = require('./config');

module.exports = task('deploy', () => Promise.resolve()
  .then(() => build())
  .then(() => {
    return new Promise((resolve, reject) => {
      const client = s3.createClient({
        s3Options: {
          accessKeyId: 'ACCESSKEY',
          secretAccessKey: 'SECRET',
          region: 'us-east-1',
          sslEnabled: true,
        },
      });
      const uploader = client.uploadDir({
        localDir: 'public',
        deleteRemoved: true,
        s3Params: {Bucket: 'BUCKET.NAME'},
      });
      uploader.on('error', reject);
      uploader.on('end', resolve);
    })
  })
  .then(() => {
    setTimeout(() => process.exit());
  }));

```
