### ISSUE TITLE
ReferenceError: run is not defined

### ISSUE THREAD

**Issue by 523334** [kriasoft/react-static-boilerplate#228]
I have an error:

```
> node tools/publish.js

Starting 'publish'...
ReferenceError: run is not defined
    at Promise.resolve.then (/home/****/tools/publish.js:32:21)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

This is my publish.js:

```js
/**
 * React Static Boilerplate
 * https://github.com/kriasoft/react-static-boilerplate
 *
 * Copyright © 2015-present Kriasoft, LLC. All rights reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.txt file in the root directory of this source tree.
 */

const path = require('path');
const firebase = require('firebase-tools');
const build = require('./build');
const task = require('./task');
const config = require('./config');

// Build and deploy the app to Firebase
module.exports = task('publish', () => {
    const ghPages = require('gh-pages');
    global.DEBUG = process.argv.includes('--debug') || false;
    const publish = (dir) => new Promise((resolve, reject) => {
        ghPages.publish(dir, {}, (err) => {
            if (err) {
                reject();
            } else {
                resolve();
            }
        });
    });

    return Promise.resolve()
        .then(() => run('clean'))
        .then(() => run('build'))
        .then(() => publish(path.join(__dirname, 'public')));
});
```

Where do I need to take the "run" from? I can do

```js
const run = require('./run');
```

but this will just create two BrowserSync sessions when I use `npm run publish`.

**Comment by mksarge** [comment]
It looks like you're using the latest build configuration (separate tasks defined in the `tools` folder), but the code in your file was written for the older build configuration (all tasks defined in `run.js`).

Try something like this:

```js
// tools/publish.js
const ghPages = require('gh-pages');
const path = require('path');
const build = require('./build');
const task = require('./task');

const publish = (dir) => new Promise((resolve, reject) => {
  ghPages.publish(dir, {}, (err) => {
    if (err) {
      reject(err);
    } else {
      resolve();
    }
  });
});

module.exports = task('publish', () => Promise.resolve()
  .then(() => build())
  .then(() => publish(path.join(__dirname, '../public')))
  .catch(console.log));
```

**Comment by 523334** [comment]
Works perfectly, thank you!
