### ISSUE TITLE
github page share problem

### ISSUE THREAD

**Issue by ahmetozalp** [kriasoft/react-static-boilerplate#233]
run.js code: https://jsfiddle.net/5fmbscz8/

> ReferenceError: tasks is not defined
>     at Object.<anonymous> (/Users/apple/Desktop/react-static-boilerplate-master/tools/run.js:22:1)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:425:7)
>     at startup (bootstrap_node.js:146:9)
>     at bootstrap_node.js:540:3
> error Command failed with exit code 1.
> git_prompt_info:5: character not in range

**Comment by mksarge** [comment]
Are you using the latest build configuration? Reference:
- https://github.com/kriasoft/react-static-boilerplate/blob/master/tools/run.js

You should remove the publish task from your file.

```js
// Remove this:
tasks.set('publish', () => {
  const remote = {
    url: 'https://github.com/<owner>/<repo>.git', // TODO: Update deployment URL
    branch: 'gh-pages',
  };
  global.DEBUG = process.argv.includes('--debug') || false;
  const spawn = require('child_process').spawn;
  const opts = { cwd: path.resolve(__dirname, './public'), stdio: ['ignore', 'inherit', 'inherit'] };
  const git = (...args) => new Promise((resolve, reject) => {
    spawn('git', args, opts).on('close', code => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`git ${args.join(' ')} => ${code} (error)`));
      }
    });
  });

  return Promise.resolve()
    .then(() => run('clean'))
    .then(() => git('init', '--quiet'))
    .then(() => git('config', '--get', 'remote.origin.url')
      .then(() => git('remote', 'set-url', 'origin', remote.url))
      .catch(() => git('remote', 'add', 'origin', remote.url))
    )
    .then(() => git('ls-remote', '--exit-code', remote.url, 'master')
      .then(() => Promise.resolve()
        .then(() => git('fetch', 'origin'))
        .then(() => git('reset', `origin/${remote.branch}`, '--hard'))
        .then(() => git('clean', '--force'))
      )
      .catch(() => Promise.resolve())
    )
    .then(() => run('build'))
    .then(() => git('add', '.', '--all'))
    .then(() => git('commit', '--message', new Date().toUTCString())
      .catch(() => Promise.resolve()))
    .then(() => git('push', 'origin', `HEAD:${remote.branch}`, '--force', '--set-upstream'));
});
```
