### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by iDVB** [kriasoft/react-static-boilerplate#255]
```
$ yarn relay
yarn relay v0.23.2
$ node ./setup --download-schema && relay-compiler --src ./src --schema ./src/schema.graphql
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: certificate has expired
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
```

Get this when I run `yarn relay`  ???

**Comment by koistya** [comment]
Thanks for heads up! Fixed
