### ISSUE TITLE
webpack error: '//' is an unknown word in _bootstrap.scss

### ISSUE THREAD

**Issue by mtrifilo** [kriasoft/react-static-boilerplate#60]
I apologize if this is in the wrong place, but I'm not too familiar with `webpack`, and I can't tell if this is an issue with `css-loader`, `postcss` or something else.

After installing `bootstrap-sass` from NPM, I tried importing it in index.js and got this error:

```
ERROR in ./~/css-loader!./~/postcss-loader!./~/bootstrap-sass/assets/stylesheets/_bootstrap.scss
/home/itxchy/www/ccf-react/node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss:7:1: Unknown word

// Core variables and mixins
^
@import "bootstrap/variables";

ERROR in ./~/css-loader!./~/postcss-loader!./~/bootstrap-sass/assets/stylesheets/_bootstrap.scss
Module build failed: TypeError: Cannot read property 'toString' of undefined
    at new Input (/home/itxchy/www/ccf-react/node_modules/postcss/lib/input.js:31:23)
    at parse (/home/itxchy/www/ccf-react/node_modules/postcss/lib/parse.js:22:17)
    at new LazyResult (/home/itxchy/www/ccf-react/node_modules/postcss/lib/lazy-result.js:61:24)
    at Processor.process (/home/itxchy/www/ccf-react/node_modules/postcss/lib/processor.js:34:16)
    at processCss (/home/itxchy/www/ccf-react/node_modules/css-loader/lib/processCss.js:165:11)
    at Object.module.exports (/home/itxchy/www/ccf-react/node_modules/css-loader/lib/loader.js:22:2)
 @ ./~/bootstrap-sass/assets/stylesheets/_bootstrap.scss 4:14-110 13:2-17:4 14:20-116

```

Here's index.js for reference. I only added the bootstrap import, a bootstrappy button, and a smaller `index.scss` file to test this:
- index.js

``` jsx
import React, { Component } from 'react';
import '../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss';
import './index.scss';

export default class extends Component {

  render() {
    return (
      <div>
        <h1>Home Page</h1>
        <button type="button" class="btn btn-danger">Dangerous Button!</button>
        <p>Coming soon.</p>
      </div>
    );
  }
}
```

The `index.scss` file with a `// comment` plus a style worked just fine. 
- index.scss

``` scss
@import '../components/variables.scss';

// test

h1 {
  font-size: 2em;
}
```

Any idea what's causing this?

**Comment by jessemezini** [comment]
Hi, i'm with the same problem :(

**Comment by frob** [comment]
maybe a webpack less issue https://github.com/webpack/less-loader/issues/59

**Comment by captainill** [comment]
I was able to resolve the same error in another project by using [postcss-scss](https://github.com/postcss/postcss-scss)

The relevant loader then used the `parser` parameter: `postcss?parser=postcss-scss`

```
      {
        test: /\.s?css$/,
        loader: ExtractTextPlugin.extract('style', 'css?sourceMap!sass!postcss?parser=postcss-scss')
      }

```

**Comment by xcarpentier** [comment]
I used this order and it's works for me : 
"style-loader!css-loader!postcss-loader!less-loader"
[...]
postcss: function () {
     return [autoprefixer];
 },
