### ISSUE TITLE
window object not available on server rendering

### ISSUE THREAD

**Issue by jyj1993126** [kriasoft/react-static-boilerplate#63]
Hi all ,
while I am using the UI Library : antd , I've got an error like this:

```
ReferenceError: window is not defined
    at Object.<anonymous> (/Applications/MAMP/htdocs/react/react-static-boilerplate/node_modules/antd/node_modules/velocity-animate/velocity.js:403:4)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/MAMP/htdocs/react/react-static-boilerplate/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Applications/MAMP/htdocs/react/react-static-boilerplate/node_modules/antd/node_modules/rc-queue-anim/lib/QueueAnim.js:23:24)
    at Module._compile (module.js:425:26)
```

I think it is because we rendered the elements on server and there is no window object without a window.
Am I right ? How could I fix it ?
Please help me .
Thanks

**Comment by dsernst** [comment]
Wrap the problematic components with:

```js
import { canUseDOM } from 'fbjs/lib/ExecutionEnvironment';

if (canUseDOM) {
  <ClientOnlyComponent />
}
```

like [in this example](https://github.com/koistya/react-static-boilerplate/blob/cc2da061a4b4424041f8652132f37c707fd0376c/app.js#L32).

**Comment by dsernst** [comment]
@jyj1993126 fixed?

**Comment by perminder-klair** [comment]
@dsernst does fixes issue for me! many thanks!

**Comment by ncksllvn** [comment]
As a get-around, you can wrap it in a `try/catch`.

**Comment by koistya** [comment]
This issues should be gone now if you're using the latest version of RSB from `master`.
